title: AI workshop
tagline: A course for Deep Learning

author:
  name: Richard Kuo
  url: https://rkuo2000.github.io/AI-workshop

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

paginate: 3

tags_path: /tags/
categories_path: /categories/

remote_theme: zivong/jekyll-theme-hydure
